name: build and test

on: 
  push:
    paths:
      - 'src/**'
      - '.github/workflows/dotnet.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/dotnet.yml'

env:
  DOTNET_VERSION: '6.0.203' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install NPM dependencies
      run: npm install

    - name: Install C# dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
